# Generated by Django 4.1.3 on 2023-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_info_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='discount/')),
            ],
        ),
        migrations.DeleteModel(
            name='UnityProduct',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='text_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='text_uz',
            new_name='name_uz',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='howtouse',
            name='img',
        ),
        migrations.AlterField(
            model_name='aboutproduct',
            name='img',
            field=models.ImageField(upload_to='about_product/'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='whouse',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whouse',
            name='title_uz',
            field=models.CharField(max_length=255),
        ),
    ]
